set_property PACKAGE_PIN T22 [get_ports {leds_4bits_tri_o[3]}]
set_property PACKAGE_PIN T21 [get_ports {leds_4bits_tri_o[2]}]
set_property PACKAGE_PIN U22 [get_ports {leds_4bits_tri_o[1]}]
set_property PACKAGE_PIN U21 [get_ports {leds_4bits_tri_o[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {leds_4bits_tri_o[3]}]
set_property PACKAGE_PIN F22 [get_ports {gpio_sw_tri_i[1]}]
set_property PACKAGE_PIN G22 [get_ports {gpio_sw_tri_i[0]}]
